## Python

* numpy
* pandas
* matplotlib

In [36]:
def square(a = 0):
    '''
    it's will return square of a number
    '''
    return a**2

In [37]:
import numpy as np

In [38]:
import pandas as pd


In [39]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [40]:
np.zeros(5 ,dtype = int)

array([0, 0, 0, 0, 0])

In [41]:
np.zeros((5,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
 np.ones((4,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
 np.random.rand(5,3)

array([[5.64115790e-02, 7.21998772e-01, 9.38552709e-01],
       [7.78765841e-04, 9.92211559e-01, 6.17481510e-01],
       [6.11653160e-01, 7.06630522e-03, 2.30624250e-02],
       [5.24774660e-01, 3.99860972e-01, 4.66656632e-02],
       [9.73755519e-01, 2.32771340e-01, 9.06064345e-02]])

rand is based on uniform distribution while randn is based on normal (Gaussian) distribution

In [46]:
np.random.randn(5,3)

array([[-1.47632969,  1.48698096, -0.02445518],
       [ 0.35555132,  0.41701111,  0.83246186],
       [-0.29339915, -0.02983857,  0.09512578],
       [ 0.66465434, -0.1402185 , -0.0331934 ],
       [-0.74907652, -0.77838201,  0.94884286]])

In [47]:
np.random.randint(3,321,(5,3))

array([[266,  37, 208],
       [ 83,  52,   4],
       [ 56, 108, 262],
       [312, 193, 220],
       [ 46, 164, 204]])

In [48]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [49]:
arr = np.arange(0,25)

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
randArray = np.random.randint(1,100,8)

In [52]:
randArray

array([83, 87, 75, 75, 88, 24,  3, 22])

In [53]:
print(randArray.max())
print(randArray.min())
print(randArray.argmax())
print(randArray.argmin())

88
3
4
6


In [54]:
randArray.dtype

dtype('int64')

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.shape

(25,)

In [57]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arrnd = arr.reshape(5,5)

In [60]:
arrnd[1:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
arr[1:5] = 12

In [62]:
arr_slice = arr[5:10]

In [63]:
arr_slice[:] = 34

In [64]:
arr

array([ 0, 12, 12, 12, 12, 34, 34, 34, 34, 34, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
slice_array = arr.copy()

In [66]:
arrnd[:2,1:3]

array([[12, 12],
       [34, 34]])

In [34]:
 arr[arr>3]

array([12, 12, 12, 12, 34, 34, 34, 34, 34, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])